version: "3"
services:
  dyndnsmasq:
    build: .
    image: jankoppe/dyndnsmasq
    cap_add:
      - NET_ADMIN
    volumes:
      - ./hosts.dyn:/etc/hosts.dyn:ro
    ports:
      - "53:53/tcp"
      - "53:53/udp"
